/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface MadnessLabyrinth {

    }
  }

  interface HTMLMadnessLabyrinthElement extends StencilComponents.MadnessLabyrinth, HTMLStencilElement {}

  var HTMLMadnessLabyrinthElement: {
    prototype: HTMLMadnessLabyrinthElement;
    new (): HTMLMadnessLabyrinthElement;
  };
  interface HTMLElementTagNameMap {
    'madness-labyrinth': HTMLMadnessLabyrinthElement;
  }
  interface ElementTagNameMap {
    'madness-labyrinth': HTMLMadnessLabyrinthElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'madness-labyrinth': JSXElements.MadnessLabyrinthAttributes;
    }
  }
  namespace JSXElements {
    export interface MadnessLabyrinthAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
